version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - REGION=${REGION}
      - INSTANCE_CONNECTION_NAME=${PROJECT_ID}:${REGION}:${INSTANCE_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - PRIVATE_IP=${PRIVATE_IP}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/service_account.json
    volumes:
      - .:/app
      - ./keys:/appp/keys
